### ISSUE TITLE
Resource spawning rework

### ISSUE THREAD

**Issue by qdaggett** [qdaggett/pest-icide#64]
Multiple spawn locations for barrels. Allows for spawning on upper levels.

**Comment by RazaKazmi** [comment]
Current Status: 
+ Resources spawning correctly
+ Spawn Points on upper and lower levels
+ Can be used for any other object in the game
Bug:
- Barrels spawn inside objects. Can fix this by adding an offset on the y.

**Comment by RazaKazmi** [comment]
- Fixed barrels spawning inside objects. Should also fix for other objects as well.
- Added Inital spawn variable to control the intial spawn amount
